### ISSUE TITLE
Add 311 complaints to NYCDB

### ISSUE THREAD

**Issue by elaby-bxd** [nycdb/nycdb#213] opened 2022-11-17 15:50 UTC
311 complaint data would be good to add to nycdb. [This article does a good job of describing the data set and an R method](https://hwangnyc.medium.com/using-r-to-access-311-service-request-from-nyc-open-data-using-socrata-open-data-api-and-the-83de00327a8c) to bring in the 311 complaint data. 

The data set is large so it might also be useful to create  aggregated views by date or views that show the last year or last 30 days to make it easier for developers.

**Comment by austensen** [comment] 2022-11-17 16:02
Hey @elaby-bxd , thanks for sharing this! We are planning to add 311 requests soon and actually just recently opened up this  issue for it - you can follow along there to get updates for when it's live. #203

**Comment by austensen** [comment] 2022-11-17 16:02
Duplicate of #203

**Closed** 2022-12-11 02:38 UTC
Labels: new dataset
